package com.meetfood.controller;

import com.meetfood.entity.Guest;
import com.meetfood.repository.GuestRepository;
import com.meetfood.statusCode.JsonResult;
import com.meetfood.statusCode.StatusCode;

import io.swagger.annotations.*;
//import net.sf.json.*;
//import net.sf.json.util.CycleDetectionStrategy;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import springfox.documentation.spring.web.json.Json;


import java.sql.Blob;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;


@Controller    // This means that this class is a Controller
@CrossOrigin
@RequestMapping(path="/guest") // This means URL's start with /user (after Application path)
@Api(value="GuestController")
public class GuestController {
    @Autowired // This means to get the bean called guestRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private GuestRepository guestRepository;

    //注册
    //@ResponseHeader(value="Access-Control-Allow-Origin:*")
    @ResponseBody
    @CrossOrigin
    @PostMapping(path="/register") // Map ONLY POST Requests
    @ApiOperation(value="输入信息（邮箱/密码/名字/年龄/电话）进行注册",notes="返回json/String")
    @ApiImplicitParams({
            @ApiImplicitParam( paramType ="query",name="email",value="注册邮箱",required=true,dataType="String"),
            @ApiImplicitParam( paramType ="query",name="password",value="注册密码",required=true,dataType="String"),
            @ApiImplicitParam( paramType ="query",name="age",value="年龄",required=true,dataType="Integer"),
            @ApiImplicitParam( paramType ="query",name="username",value="用户名称",required=true,dataType="String"),
            @ApiImplicitParam( paramType ="query",name="teleNumber",value="手机号码",required=true,dataType="String")
    })
    public JsonResult registerGuest (@RequestParam String email
            , @RequestParam String password
            , @RequestParam Integer age
            , @RequestParam String username
            , @RequestParam String teleNumber) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        //header("Access-Control-Allow-Origin：*");
        boolean emailCheck = false;

        // 判断邮箱格式是否正确：合法的邮箱名中至少要包含"@", 并且"@"是在"."之前
        // 获取邮箱中"@"符号的位置
        int index1 = email.indexOf("@");
        // 获取邮箱中"."号的位置
        int index2 = email.indexOf('.');
        // 判断必须包含"@"符号，且"@"必须在"."之前
        if (index1 != -1 && index2 > index1) {
            emailCheck = true;
        } else {
            emailCheck = false;
        }
        //查询邮箱
        if (emailCheck != false) {
            if (guestRepository.findByEmail(email).size() == 0) {
                Guest n = new Guest();
                //新建用户
                n.setEmail(email);
                n.setPassword(password);
                n.setAge(age);
                n.setUsername(username);
                n.setTeleNumber(teleNumber);
                //n.setPhoto("/photo");
                guestRepository.save(n);
                return  new JsonResult(StatusCode.SUCCESS.getCode(), new Date());
            } else return  new JsonResult(StatusCode.FAIL_REGISTERED.getCode(),new Date());
        }else return  new JsonResult(StatusCode.FAIL_FORMAT.getCode(), new Date());
    }

    //登录
    @ResponseBody
    @CrossOrigin
    @PostMapping(path="/login") // Map ONLY POST Requests
    @ApiOperation(value="使用邮箱密码进行登录账号",notes="返回json/String")
    @ApiImplicitParams({
            @ApiImplicitParam( paramType ="query",name="email",value="登录邮箱",required=true,dataType="String"),
            @ApiImplicitParam( paramType ="query",name="password",value="登陆密码",required=true,dataType="String")
    })
    public JsonResult loginGuest (@RequestParam String email,
                                @RequestParam String password) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        if(guestRepository.findByEmail(email).size()!= 0){
            if(guestRepository.findByEmailAndPassword(email,password).size()!= 0){
                List<Guest> guest = guestRepository.findByEmail(email);
                return new JsonResult(StatusCode.SUCCESS.getCode(), guest, new Date());
            }else return new JsonResult(StatusCode.FAIL_PASS.getCode(), new Date());
        }else return new JsonResult(StatusCode.NOT_EXIST.getCode(), new Date());
    }
    //修改信息
    @PutMapping(path = "/revise")
    @CrossOrigin
    @ApiOperation(value = "修改用户信息",notes = "返回json")
    @ApiImplicitParams({
            @ApiImplicitParam( paramType = "query",name = "age",value = "当前用户年龄",required = true,dataType = "Integer"),
            @ApiImplicitParam( paramType = "query",name = "username",value = "用户名称",required = true,dataType = "String"),
            @ApiImplicitParam( paramType = "query",name = "email",value = "用户邮箱",required = true,dataType = "String"),
            @ApiImplicitParam( paramType = "query",name = "teleNumber",value = "用户号码",required = true,dataType = "String")
    })
    public @ResponseBody JsonResult reviseGuest (//@RequestParam Integer id,
                                             @RequestParam Integer age,
                                             @RequestParam String username,
                                             @RequestParam String email,
                                             @RequestParam String teleNumber){
        try {
            Guest guest = new Guest();
            guest = guestRepository.findById(1).get();
            guest.setUsername(username);
            guest.setAge(age);
            guest.setEmail(email);
            guest.setTeleNumber(teleNumber);

            guestRepository.save(guest);

            return new JsonResult(StatusCode.SUCCESS.getCode(), new Date());

        }catch (Exception e){
            return new JsonResult(StatusCode.SYS_ERROR.getCode(), new Date());

        }
    }
    //返回所有信息
    @GetMapping(path = "/message")
    @CrossOrigin
    @ApiOperation(value = "根据id返回信息",notes = "返回json")
    @ApiImplicitParam(paramType = "query",name = "id",value = "客人id",required = true,dataType = "Integer")
    public @ResponseBody   JsonResult  returnMessage(@RequestParam Integer id){
        return new JsonResult(StatusCode.SUCCESS.getCode(),guestRepository.findMessageById(id),new Date());
    }


    //查看所有用户
    @GetMapping(path="/all")
    @CrossOrigin
    public @ResponseBody Iterable<Guest> getAllUsers() {

        return guestRepository.findAll();
    }
}
