package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

//import json.LoginResult;
//import json.StatusCode;


@Controller    // This means that this class is a Controller
@RequestMapping(path="/user") // This means URL's start with /demo (after hello.Application path)
public class UserController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	//注册
    @GetMapping(path="/register") // Map ONLY GET Requests
    public @ResponseBody String register (@RequestParam String email
            , @RequestParam String password
            ,@RequestParam Integer type
            ,@RequestParam String name) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        //User check = new User();
        if(userRepository.findByEmail(email).size() == 0){
            User n = new User();

            n.setEmail(email);
            n.setPhoto("10000");
            n.setName(name);
            n.setPassword(password);
            n.setType(type);
            userRepository.save(n);
            return "注册成功!";

        }else return "该邮箱已被注册！";
    }
    //登录
    @GetMapping(path="/login") // Map ONLY GET Requests
    public @ResponseBody String register (@RequestParam String email
            , @RequestParam String password) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        //User check = new User();
        if(userRepository.findByEmail(email).size()!= 0){
            if(userRepository.findByEmailAndPassword(email,password).size()!= 0){
                return "登陆成功";
            }else return "密码错误";
        }else return "未注册";
    }
    /*
    @GetMapping(path="/login") // Map ONLY GET Requests
    public @ResponseBody LoginResult register (@RequestParam String email
            , @RequestParam String password) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        //User check = new User();
        if(userRepository.findByEmail(email).size()!= 0){
            if(userRepository.findByEmailAndPassword(email,password).size()!= 0){
                return new LoginResult(StatusCode.SUCCESS.getCode(), StatusCode.SUCCESS.getMessage(), new Date());
            }else return new LoginResult(StatusCode.PASS_ERROR.getCode(),StatusCode.PASS_ERROR.getMessage(), new Date());
        }else return new LoginResult(StatusCode.NOT_REGISTER.getCode(),StatusCode.NOT_REGISTER.getMessage(), new Date());
    }*/
    //查看所有用户
    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
	}
}
